---
title: "music_emotions"
output: html_document
---

# Load Packages

```{r}
library("corrplot")
library("janitor")
library("tidyverse")
```

# DATA

## Read in Data

```{r}
df.exp1 = read_csv("../../Data/exp1.csv")
```

## Wrangle data

```{r}
df.exp1 = df.exp1 %>% 
  select(-c(`Consent Form:                                                       DESCRIPTION: You are invited to participate in a research study on how different genres and tempos of music affect teenager’s emotions. Hopefully, based on the data, we can see what type of music at what tempo has the most positive/negative impact on teenager’s moods. You will be asked to listen to 15 20-to-30-seconds-long recordings of different music at different tempos and rate your mood after listening to each one.                                                                              TIME INVOLVEMENT: Your participation will take approximately 8-10 mins to finish the survey           RISKS AND BENEFITS: The risks associated with this study are none. Study data will be stored securely, minimizing the risk of confidentiality breach. We cannot and do not guarantee or promise that you will receive any benefits from this study. Your decision of whether or not to participate in this study will not affect your grades in school.                                               PARTICIPANT’S RIGHTS: If you have read this form and have decided to participate in this project, please understand your participation is voluntary and you have the right to withdraw your consent or discontinue participation at any time without penalty or loss of benefits to which you are otherwise entitled. The alternative is not to participate. You have the right to refuse to answer particular questions. The results of this research study may be presented at scientific or professional meetings or published in scientific journals. Your individual privacy will be maintained in all published and written data resulting from the study.`, Timestamp, Score)) %>% 
  clean_names() 


df.exp1 = df.exp1 %>% 
  mutate(rename(., "po" = please_click_the_link_below_to_listen_to_your_audio_whats_your_mood_after_listening_to_the_audio_from_a_scale_of_1_10_po),
         rename(., "ps" = please_click_the_link_below_to_listen_to_your_audio_whats_your_mood_after_listening_to_the_audio_from_a_scale_of_1_10_ps),
         rename(., "pf" = please_click_the_link_below_to_listen_to_your_audio_whats_your_mood_after_listening_to_the_audio_from_a_scale_of_1_10_pf),
         rename(., "ro" = please_click_the_link_below_to_listen_to_your_audio_whats_your_mood_after_listening_to_the_audio_from_a_scale_of_1_10_ro),
         rename(., "rs" = please_click_the_link_below_to_listen_to_your_audio_whats_your_mood_after_listening_to_the_audio_from_a_scale_of_1_10_rs),
         rename(., "rf" = please_click_the_link_below_to_listen_to_your_audio_whats_your_mood_after_listening_to_the_audio_from_a_scale_of_1_10_rf),
         rename(., "rbo" = please_click_the_link_below_to_listen_to_your_audio_whats_your_mood_after_listening_to_the_audio_from_a_scale_of_1_10_rbo),
         rename(., "rbs" = please_click_the_link_below_to_listen_to_your_audio_whats_your_mood_after_listening_to_the_audio_from_a_scale_of_1_10_rbs),
         rename(., "rbf" = please_click_the_link_below_to_listen_to_your_audio_whats_your_mood_after_listening_to_the_audio_from_a_scale_of_1_10_rbf),
         rename(., "ho" = please_click_the_link_below_to_listen_to_your_audio_whats_your_mood_after_listening_to_the_audio_from_a_scale_of_1_10_ho),
         rename(., "hs" = please_click_the_link_below_to_listen_to_your_audio_whats_your_mood_after_listening_to_the_audio_from_a_scale_of_1_10_hs),
         rename(., "hf" = please_click_the_link_below_to_listen_to_your_audio_whats_your_mood_after_listening_to_the_audio_from_a_scale_of_1_10_hf),
         rename(., "co" = please_click_the_link_below_to_listen_to_your_audio_whats_your_mood_after_listening_to_the_audio_from_a_scale_of_1_10_co),
         rename(., "cs" = please_click_the_link_below_to_listen_to_your_audio_whats_your_mood_after_listening_to_the_audio_from_a_scale_of_1_10_cs),
         rename(., "cf" = please_click_the_link_below_to_listen_to_your_audio_whats_your_mood_after_listening_to_the_audio_from_a_scale_of_1_10_cf))

df.exp1 = df.exp1 %>% 
  mutate(rename(., "current_mood" = what_is_your_current_mood_from_a_scale_of_1_10)) %>% 
  select(po:current_mood)


```

##To do

```{r}

##repeat for all variables
df.exp1 = df.exp1 %>% 
  mutate(po = str_extract(po, "[:digit:]"),
         ps = str_extract(ps, "[:digit:]"),
         pf = str_extract(pf, "[:digit:]"),
         ro = str_extract(ro, "[:digit:]"),
         rs = str_extract(rs, "[:digit:]"),
         rf = str_extract(rf, "[:digit:]"),
         rbo = str_extract(rbo, "[:digit:]"),
         rbs = str_extract(rbs, "[:digit:]"),
         rbf = str_extract(rbf, "[:digit:]"),
         ho = str_extract(ho, "[:digit:]"),
         hs = str_extract(hs, "[:digit:]"),
         hf = str_extract(hf, "[:digit:]"),
         co = str_extract(co, "[:digit:]"),
         cs = str_extract(cs, "[:digit:]"),
         cf = str_extract(cf, "[:digit:]"),
         current_mood = str_extract(current_mood, "[:digit:]"))

```

```{r}

df.exp1 = df.exp1 %>% 
  mutate(participant = rep(1:12)) %>% 
  relocate(participant) 

df.exp1.long = df.exp1 %>% 
  pivot_longer(cols = -participant,
               names_to = "music",
               values_to = "response")

df.exp1.long = df.exp1.long %>% 
  filter(music != "current_mood") %>% 
  mutate(genre = rep(c("pop", "rock", "rnb", "hiphop", "classical"), each = 3, times = 12),
         tempo = rep(c("original", "slow", "fast"), time = 60)) %>% 
  select(-music)

```

```{r}

ggplot(data = df.exp1.long,
       aes(x = genre,
           y = response,
           group = tempo,
           color = tempo,
           fill = tempo)) + 
  geom_point() + 
  stat_summary(fun.data = "mean_cl_boot",
               shape = 21,
               size = 1,
               position = position_dodge(width = .5)) +
  scale_color_brewer("Set1") +
  scale_fill_brewer("Set1")

ggsave("../../figures/genre_tempo_plot.pdf",
       height = 3,
       width = 5)

```


```{r}

ggplot(data = df.exp1.long,
       aes(x = genre,
           y = response,
           group = genre,
           color = genre,
           fill = genre)) + 
  geom_point() + 
  stat_summary(fun.data = "mean_cl_boot",
               shape = 21,
               size = 1,
               position = position_dodge(width = .5)) +
  scale_color_brewer("Set1") +
  scale_fill_brewer("Set1")

ggsave("../../figures/genre_plot.pdf",
       height = 3,
       width = 5)

```



```{r}

ggplot(data = df.exp1.long,
       aes(x = tempo,
           y = response,
           group = tempo,
           color = tempo,
           fill = tempo)) +
  geom_point() + 
  stat_summary(fun.data = "mean_cl_boot",
               shape = 21,
               size = 1,
               position = position_dodge(width = .5)) +
  scale_color_brewer("Set1") +
  scale_fill_brewer("Set1")

ggsave("../../figures/tempo_plot.pdf",
       height = 3,
       width = 5)

```


```{r}

cor = df.exp1 %>% 
  select(-participant) %>% 
  mutate(across(everything(), .fns = as.numeric)) %>% 
  cor(.)
```

```{r}
corrplot(cor, type = "upper")

ggsave("../../figures/correlation_plot.pdf",
       height = 3,
       width = 5)
```